### PR TITLE
Added `help` component to provide “Getting Started” information

### LINKED ISSUE #4: MyneChat getting started guide
# Background

To start working with MyneChat locally, you need to either run an interconnected network or use our `mocks` server. The last process is documented in the README, but the first one isn't.

Also, if you go to https://app.myne.chat/, it's not immediately obvious what to do or how to get started. The application on its own can't actually do anything without a HOPRd node, which needs to be connected as part of a network of funded nodes. This setup is a bit cumbersome and ever worse, undocumented.

# Introduction

Provide instructions on how to run an interconnected HOPR network and how to start MyneChat and connect to it. Improve the README to point out these steps and use the "quick settings" URL command. Finally, when starting MyneChat, we should provide a series of messages to the users (see #61), which showcase to the user what to do and how to get started.

# Tasks

- [x] https://github.com/hoprnet/hoprnet/issues/3329
- [x] #103
- [x] #108

### PR DESCRIPTION
**Pull request by jjperezaguinaga**
- Provided a JIT parser of our README to allow anyone to update the “Help” section of our app
- Added new `displayHelp` state variable to showcase control of this content via the UI
- Minor refactor on `Chat` component to allow dynamic displaying of content in via `ChatView`
- Fixes #4

### CODE REVIEW

**Comment by nionis** [comment]
I don't think we need this? if this is for #4 am pretty sure it's not what it's intended, @tolbrino can u add description into #4?

**Comment by tolbrino** [comment]
That issue was certainly not very specific. I don't explicitly like to include the README in the app, since its not meant as user documentation. I'd ask @SCBuergel @Jaguaras @thewanderingeditor for input on this one.

**Comment by jjperezaguinaga** [comment]
Agreed. Happy to use whatever information, the benefit is that this can be imported via a Markdown file. Putting this as a draft for the time being.

**Comment by jjperezaguinaga** [comment]
This issue is slowly becoming stale. As we have already #4 being tackled in #100, this makes no longer sense so will close it down while we keep the learnings within this PR.

**Pull request closed without merging**
