### PR TITLE
Extend Myne.Chat To Include Earning Indicators Bounty

### PR DESCRIPTION
**Pull request by szczebel1995**
https://user-images.githubusercontent.com/26637546/181654299-48b95c6c-939c-4966-9377-131e48c08b56.mp4

This is a pull request for this bounty: https://gitcoin.co/issue/28980 

Some notes:
- Tested it with the local cluster setup but all tickets there were winning and the win ratio was always 0 so I opted out to just pool tickets statistics endpoint of the node and show coin rain animation when total number of tickets increased.
- Don't really know whats the normal range of token rewards in production environment so I made it always rain 10 coins which looks good.
- I made the animation function accept parameters to control it so tweaking it should be easy and quick.
- Decided to go with canvas animation because of better performance across all browsers.
- Currently balance is pulled every 10s and tickets check that can trigger coin animation is pulled every 24-30s.

### CODE REVIEW

**Comment by nionis** [comment]
hey @szczebel1995, awesome work, would it be possible to change the location of the coin drop to the main chat section for a small tip? thanks

**Comment by szczebel1995** [comment]
Sure no problem, will tweak it soon.

**Comment by nionis** [comment]
gotta merge this PR already as the deadline has passed, I consider this bounty complete, thanks @szczebel1995

**Review by nionis — APPROVED** [review]
fixing deployment issue on develop

**Pull request merged**
