### PR TITLE
Fixes #114 - UI Improvements

### LINKED ISSUE #114: Chat.UI improvements: typography, linking, appearance of messages
### Describe the feature you'd like
- Improve the Ui by-> please realize the raised comments and do come back when questions arise:
https://usepastel.com/link/pwed5/

### PR DESCRIPTION
**Pull request by QuinsZouls**
### List of changes 7/8
- [Add roboto medium italic font](https://github.com/hoprnet/myne-chat/commit/c480eec69c4b2ba58616949f4d6dd333dbe52a88)
- [Change label alignment](https://github.com/hoprnet/myne-chat/commit/5c1336a5b8520a2f87a021b0b5cc41c797e08d4a)
- [Delete dev emoji](https://github.com/hoprnet/myne-chat/commit/dfa002f328e42cdc1fd5988e1d1010d3fe356795)
- [Change connected icons](https://github.com/hoprnet/myne-chat/commit/2bddadde1b9d690ead3b557f15bccd097c510d15)
- [Adjust HOPR link style](https://github.com/hoprnet/myne-chat/commit/14971c97534361c068e7b36df20df917b2ae32f9)
- [Adjust chat bar height](https://github.com/hoprnet/myne-chat/commit/07318dcd3316d161c8fdd8d0c7efa491f892b22a)
- [Limit chat message width to 70%](https://github.com/hoprnet/myne-chat/commit/901c23cbac9a52124f3dc319441f71f66cc9b77d)

### To-do
- Animate arrival/appearance of new chat bubbles

### CODE REVIEW

**Comment by ReinhardSchmidt** [comment]
About the change of the font into Roboto: somehow I still do see in three Browsers the Gerstner. How is that possible?

**Comment by QuinsZouls** [comment]
> About the change of the font into Roboto: somehow I still do see in three Browsers the Gerstner. How is that possible?

The Gensher font is still needed? because the repository have these two fonts locally, if it's not needed, i can delete Gensher font and only use Roboto

**Comment by ReinhardSchmidt** [comment]
Yes please, delete the Gerstner in the chat repository. Replace with Roboto. Many thanks 👍

**Comment by jjperezaguinaga** [comment]
This will be reviewed and approved by @ReinhardSchmidt

**Review by ReinhardSchmidt — APPROVED** [review]

**Comment by ReinhardSchmidt** [comment]
@jjperezaguinaga Can you fix the conflicting files issue in "src/components/mocks-server.tsx"?

**Comment by ReinhardSchmidt** [comment]
@jjperezaguinaga can you fix the confliciting files issue in "src/components/mocks-server.tsx"?

**Comment by jjperezaguinaga** [comment]
Merging as @ReinhardSchmidt 's review was given and got dismissed by a conflict update.

**Review by jjperezaguinaga — APPROVED** [review]

**Pull request merged**
