### PR TITLE
Components documentation

### LINKED ISSUE #3: MyneChat technical documentation for developers
# Background

MyneChat relies on three main technologies: Next.js, Grommet, and Immer.js. On top of that, it uses Websockets and an API to communicate with the HOPRd node and uses React hooks constantly to update a global state. These things are only obvious after looking and working with the code. Ideally, developers trying to familiarize themselves with MyneChat and how it was built, would rather look at some documentation than inspect the code from scratch (which is always an option anyway).

In addition, we make extensive use of components in MyneChat, but they can't really function in isolation due to #98. We should make a note of this by documenting the structure of the components somehow so people know what can be reused for their own apps or for a possible MyneChat fork.

# Introduction

For this task, we need to provide users with documentation on the following topics:

- Tech stack and general application architecture
- Current code structure, and common conventions used within MyneChat
- Current components architecture, and reusability for other apps
- Steps to create a fork of MyneChat if needed

# Tasks

- [x] Create a publicly accessible documentation page focused on MyneChat only
  - [x] #104
  - [x] #105
  - [x] #106
  - [x] #107

# Definition of done

The aforementioned documentation can be found in an accessible URL. It can answer the questions "How was MyneChat build?", "What should I do if I want to improve MyneChat?", "What could I reuse from MyneChat to use in my HOPR app?", and "How could I build my own themed chat by forking MyneChat?".

### LINKED ISSUE #4: MyneChat getting started guide
# Background

To start working with MyneChat locally, you need to either run an interconnected network or use our `mocks` server. The last process is documented in the README, but the first one isn't.

Also, if you go to https://app.myne.chat/, it's not immediately obvious what to do or how to get started. The application on its own can't actually do anything without a HOPRd node, which needs to be connected as part of a network of funded nodes. This setup is a bit cumbersome and ever worse, undocumented.

# Introduction

Provide instructions on how to run an interconnected HOPR network and how to start MyneChat and connect to it. Improve the README to point out these steps and use the "quick settings" URL command. Finally, when starting MyneChat, we should provide a series of messages to the users (see #61), which showcase to the user what to do and how to get started.

# Tasks

- [x] https://github.com/hoprnet/hoprnet/issues/3329
- [x] #103
- [x] #108

### PR DESCRIPTION
**Pull request by jjperezaguinaga**
The PR is meant to tackle #3 and provide MyneChat developers with an insight on the project's architecture and features, with the goal of allowing them to easily modify it so they can create their own version.

### Preview

The storybook preview is created per PR and can be seen in https://61eede5cc1e9cb003a97ad08-brlfkxdwmc.chromatic.com/. You can test this PR locally by running `yarn` (multiple dependencies were included) and `yarn storybook`. Components and content were documented using MDX files which can be changed if needed.

### Notes
- Ensure #99 has been merged for easy testing and make sure that it points to the right URL when clicking the Gitpod.io button on the README.
- Included [Storybook](https://storybook.js.org/) to render components and document architecture
- Included [Chromatic](https://www.chromatic.com/) for easy Storybook deployment
- ~Fixes #4~ Fixes #3

### CODE REVIEW

**Comment by jjperezaguinaga** [comment]
Getting started video available in https://vimeo.com/668655806/95081125b1, instructions to be shown in docs.hoprnet.org. This issue will only be closed after the latter is added.

**Comment by jjperezaguinaga** [comment]
We shifted the focus of this PR partially to cater more to #3 rather than #4 as it seems that we are looking to have MyneChat documentation available within our `hoprnet` ecosystem. This is sadly the second time the requirements weren't clear enough and some work was misdirected (see #60).

For now, I'll hold on to any documentation unless focused on the development of MyneChat which this PR should suffice and is anyway part of the epic. I'll move on to #101 and do any documentation if needed outside of GitHub's tooling.

**Comment by jjperezaguinaga** [comment]
This PR fixes https://github.com/hoprnet/myne-chat/issues/3, which is the one-before the last task to complete MyneChat `0.2`. Here are some quick URL links to speed up the review process:

- Technical documentation via Storybook in https://61eede5cc1e9cb003a97ad08-tqujlryrcg.chromatic.com/
- Latest version of MyneChat w/mocks connection UI in https://myne-chat-cvne8p796-hoprnet.vercel.app/?development=enabled

**Review by tolbrino — APPROVED** [review]
Good first step towards a technical documentation for Myne Chat. It still has gaps, and deployment needs to be solved, but that can be handled in separate PRs.

**Pull request merged**
